#!/bin/sh
RABOMSDIR="/usr/share/raboms"

set -e

## Cambio de propiedad sin usar recursividad para compatibilidad con lintian
## https://lintian.debian.org/tags/maintainer-script-should-not-use-recursive-chown-or-chmod.html
chown root:audio $RABOMSDIR/
chown root:audio $RABOMSDIR/*
chown root:audio $RABOMSDIR/src/*
chown root:audio $RABOMSDIR/src/images/*
## Cambio de permisos sin usar recursividad para compatibilidad con lintian
## https://lintian.debian.org/tags/maintainer-script-should-not-use-recursive-chown-or-chmod.html
chmod 775 $RABOMSDIR/
chmod 775 $RABOMSDIR/*
chmod 775 $RABOMSDIR/src/*
chmod 775 $RABOMSDIR/src/images/*

